---
#
# My notebook development rig
#
# ansible-playbook -K dev.yml
#
- hosts: dev
  user: map7
  sudo: yes
  vars:
    main_user: map7
  vars_files:
    - "vars/defaults.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/Debian-testing.yml"

  tasks:
    - include: common/tasks/system.yml
    - include: common/tasks/office.yml 
    - include: common/tasks/multimedia.yml
    - include: common/tasks/gnome-do.yml

    - include: common/tasks/nvidia.yml 
    - include: common/tasks/lvm.yml
    - include: common/tasks/x2go.yml

    - include: common/tasks/dropbox.yml
    - include: common/tasks/mozilla.yml
    #- include: common/tasks/skype.yml # Skype didn't work, it's a pain & firefox hello is better.

    - include: common/tasks/postgresql.yml
    - include: common/tasks/programming.yml 
    - include: common/tasks/wkhtmltopdf.yml

  handlers:
    - include: common/handlers/handlers.yml    
