#!/usr/bin/env ansible-playbook
---
- name: Install and configure
  hosts: all
  become: true

  vars_files:
    - custom.yml
    - secret.yml

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Set the AWS and Letsencrypt staging facts
      ansible.builtin.set_fact:
        aws: "{{ lookup('ansible.builtin.env', 'AWS_EC2') == 'true' }}"
        letsencrypt_staging: "{{ [lookup('ansible.builtin.env', 'LETSENCRYPT_STAGING') | lower | default('no')] }}"

  roles:
    - role: system
      tags:
        - system

    - role: geerlingguy.docker
      tags:
        - docker

    - role: docker
      tags:
        - docker

    - role: fail2ban
      when: enable_fail2ban | default(False)
      tags:
        - fail2ban

    - role: dns
      when: enable_adguard_unbound_doh | default(False)
      tags:
        - dns

    - role: watchtower
      tags:
        - watchtower

    - role: authelia
      tags:
        - authelia

    - role: web
      tags:
        - web

    - role: wireguard
      tags:
        - wireguard

    - role: ssh
      tags:
        - ssh
