---

- name: install python to run ansible playbook
  hosts: ubuntu
  become: true
  gather_facts: False
  tasks:
  - name: install python 2.7 on ubuntu
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - name: make apt frontend noninteractive
    raw: export DEBIAN_FRONTEND=noninteractive

- name: Include a play after another play
  import_playbook: webservers.yml
  tags: webservers
