#!/usr/bin/env ansible-playbook
---
- name: xsos install
  hosts: all

  tasks:
  - name: download_binary_gpg_key
    get_url:
      url: http://b19.org/rsaw.pgp
      dest: /tmp/rsaw.pgp

  - name: convert_key_to_asiiarmor
    command: "gpg --keyring /tmp/rsaw.keyring --no-default-keyring --import /tmp/rsaw.pgp"
    args:
      creates: /tmp/rsaw.keyring
  - name: convert_key_to_asiiarmor2
    command: "gpg --keyring /tmp/rsaw.keyring --no-default-keyring --export -a --output /tmp/rsaw.pgp.asc"
    args:
      creates: /tmp/rsaw.pgp.asc

  - name: rsawhill_key
    rpm_key:
      state: present
      key: /tmp/rsaw.pgp.asc

  - name: rsawhill_repo
    yum:
      name: http://people.redhat.com/rsawhill/rpms/latest-rsawaroha-release.rpm
      state: latest

  - name: xsos_and_rsar_RPMs
    yum:
      name:
      - xsos
      - rsar
      state: latest
...