# code: language=ansible
# Ansible Playbook for AryaOS
#
# Copyright Sensors & Signals LLC https://www.snstac.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- name: Default
  hosts: all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update repository index (Debian)
      tags: always
      ansible.builtin.apt:
        cache_valid_time: 86400
      changed_when: false
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  roles:
    - role: stage-base
    - role: stage-aryaos
    - role: stage-pytak
    - role: stage-node-red
    - role: stage-docker
    - role: stage-adsbcot
    - role: stage-aiscot
    - role: stage-dronecot
