---
- name: Default
  hosts: all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update repository index (Debian)
      tags: always
      ansible.builtin.apt:
        cache_valid_time: 86400
      changed_when: false
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  roles:
    - role: stage-base
    - role: stage-aryaos
    - role: stage-pytak
    - role: stage-node-red
    - role: stage-docker
    - role: stage-adsbcot
    - role: stage-aiscot
    - role: stage-dronecot
