#!/usr/bin/env ansible-playbook
---

- import_playbook: asserts.yml

- name: configure backpninja for nodes
  hosts: backupninja
  gather_facts: False

  tasks:

    - delegate_to: localhost
      block:
        - { make: { chdir: ., file: dups.mk, target: main }, run_once: True }
        - { find: { path: 'tmp/{{ inventory_hostname }}/', patterns: '*.dup' }, register: find }
    - copy:
        src: '{{ item.path }}'
        dest: '/etc/backup.d'
        mode: 0600
      become: True
      loop: '{{ find.files }}'
      loop_control: { label: '{{ item.path }}' }

