---
- name: Handle MySQL Database Server Crash
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Restart MySQL Service
      service:
        name: mysqld
        state: restarted

    - name: Ensure MySQL is running
      service:
        name: mysqld
        state: started
        enabled: yes