---
- hosts: all
  tasks:
    - name: Check if a file exists
      stat:
        path: /tmp/myfile.txt
      register: file_info
    - name: Print file info
      debug:
        msg: "File exists: {{ file_info.stat.exists }}"