---
  - name: "Playing with Ansible."
# Ansible Playbook will run on the Localhost where AWX is installed
    hosts: localhost
    connection: local
    tasks:
# Below task will execute the list of directories and files present
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"
# The Output of the above task will be displayed on the Screen
    - debug: var=output.stdout_lines
