---
- name: Troubleshoot ServiceNow Login Issues
  hosts: localhost
  tasks:
    - name: Check DNS resolution for servicenow instance
      command: nslookup your-servicenow-instance.service-now.com
      register: dns_check
      changed_when: false

    - name: Debug DNS resolution output
      debug:
        var: dns_check.stdout_lines

    - name: Check connectivity to ServiceNow instance on port 443
      command: curl -kI https://your-servicenow-instance.service-now.com | head -n 1
      register: connectivity_check
      changed_when: false

    - name: Debug connectivity output
      debug:
        var: connectivity_check.stdout_lines

    - name: Check if firewall rules are blocking access
      command: sudo iptables -L
      register: firewall_rules
      changed_when: false

    - name: Debug firewall rules
      debug:
        var: firewall_rules.stdout_lines

    - name: Check system date and time
      command: date
      register: date_time_check
      changed_when: false

    - name: Debug system date and time
      debug:
        var: date_time_check.stdout_lines