---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  tasks:
  - name: Check Apache Process List
    shell:
      command: "ps aux | grep apache"
    register: apache_process_list

  - name: Start Apache Service if it's not running
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Ensure Apache PID File exists
    file:
      path: /var/log/apache2.pid
      state: present
      owner: root
      group: root

  - name: Check if the PID file is being created by Apache
    shell:
      command: "cat /var/log/apache2.pid | grep apache"
    register: pid_file_contents

  - name: Update Apache Process List
    shell:
      command: "ps aux | grep apache"
    when: True