---
- name: Ensure Apache is running
  hosts: all
  become: yes
  tasks:
    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Verify Apache process is running
      command: pgrep apache2 || pgrep httpd
      register: apache_process_check
      ignore_errors: true

    - name: Restart Apache if not running
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted
      when: apache_process_check.rc != 0