---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed and started
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create a simple index.html file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Hello, World!</h1></body>
          </html>

    - name: Ensure firewall allows HTTP traffic
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: true
        immediate: yes
        state: enabled