---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Attempt to login to ServiceNow
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user"
        method: GET
        user: your_username
        password: your_password
        validate_certs: yes
        status_code: 200
      register: service_now_login

    - name: Display login result
      debug:
        var: service_now_login.status