---
- name: Check Apache Status
  hosts: all
  become: true
  tasks:
  - name: Check if Apache is running
    service:
      name: apache2
      state: started
      enabled: yes
    register: apache_status
  
  - name: Show Apache status
    debug:
      msg: "{{ apache_status }}"