---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure package is installed
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes