---
- name: Apache Server Not Responding
  hosts: servers
  become: yes

  vars:
    server_name: your-server-name
    apache_version: "{{ apache_version | default('2.4.53') }}"

  tasks:

  - name: Check Apache Process List
    shell:
      command: "ps aux | grep {{ server_name }}"
      notify: restart apache

  - name: Restart Apache Server
    service:
      name: apache2
      state: restarted
      enabled: yes