---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Attempt to login to ServiceNow using HTTP request
      uri:
        url: "https://<instance_name>.service-now.com/api/now/table/sys_user?sysparm_limit=1"
        method: GET
        user: "<username>"
        password: "{{ service_now_password }}"
        validate_certs: no
        status_code: 200
      register: response

    - name: Debug the response
      debug:
        var: response.status

    - name: Fail if login is not successful
      fail:
        msg: "Failed to log in to ServiceNow"
      when: response.status != 200