---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed and running
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is started and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"