---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  tasks:
  - name: Check Process List
    shell: "ps aux | grep apache2"
    register: process_list_output

  - name: Parse Process List Output
    debug: msg="Process List:\n{{ process_list_output.stdout }}"

  - name: Restart Apache Web Server
    uri:
      url: http://localhost:80/status
      method: GET
      body: '{"status": "not responding"}'
      auth:
        username: root
        password: root

  - name: Log Restart Event
    debug: msg="Apache Web Server Restarted Successfully!"