---
- name: Restart Visual Studio Code on macOS
  hosts: localhost
  become: no
  tasks:
    - name: Kill Visual Studio Code process
      command: pkill -f "Visual Studio Code"
      ignore_errors: yes

    - name: Launch Visual Studio Code
      command: open -a "Visual Studio Code"