---
- name: Apache Web Server Check
  hosts: localhost
  become: yes

  roles:
    - ansible-role-apache
  tasks:
   - name: "Check Apache status"
     uri: http://localhost:9000/status
     register: status
   - when: status.success is False
   - name: "Check if process list shows 'apache'"
     uri: http://localhost:9001/check
     register: apache_list
   - when: apache_list.success is False
   - name: "Take action if Apache not found"
     uri: http://localhost:9002/check
     register: apache_found
   - when: apache_found.success is False
   - name: "Install and start Apache"
     uri: http://localhost:9003/install
     notify: restart apache