---
- name: Restart Apache
  hosts: all
  become: yes

  tasks:
  - name: Check Apache status
    command: "service apache2 status"
    register: apache_status

  - name: Restart Apache if not running
    service:
      name: apache2
      state: restarted
      enabled: no
    when:
      - not apachestatus.stat.exists()