---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no
  vars:
    sn_instance: "your_service_now_instance"
    sn_username: "your_username"
    sn_password: "your_password"

  tasks:
    - name: Ensure ServiceNow instance is reachable and login credentials are valid
      uri:
        url: "https://{{ sn_instance }}.service-now.com/api/now/table/incident?sysparm_limit=1"
        method: GET
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        validate_certs: no
        status_code: 200
      register: response

    - name: Debug response for troubleshooting if needed
      debug:
        var: response