---
- name: Check Apache Web Server
  hosts: localhost
  become: yes

  roles:
    - ansible-role-apache-check

  tasks:
  - name: Get Process List
    uri:
      url: http://localhost:8080/health_check
      method: GET
      status_code: 200
      content_type: application/json

  - name: Parse JSON
    json:
      level: debug
      source: "{{ lookup('uri', 'http://localhost:8080/health_check') | json }}"

  - name: Check Apache Status
    uri:
      url: http://localhost:8080/status
      method: GET
      status_code: 200
      content_type: application/json

  - name: Print Results
    debug:
      msg: "{{ lookup('uri', 'http://localhost:8080/health_check') | json }} and {{ lookup('uri', 'http://localhost:8080/status') | json }}"