---
- name: Apache Web Server Check
  hosts: localhost
  become: yes

  tasks:
  - debug:
      msg: "Apache is not responding"
    when: apache_status == 'down'

  - debug:
      msg: "Apache status is {{ apache_status }}"
    when: apache_status != 'up'