---
- name: ServiceNow Access Check Playbook
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Attempt to authenticate to ServiceNow using HTTP API
      uri:
        url: "https://your-instance.service-now.com/api/now/table/incident"
        method: GET
        user: your_username
        password: your_password
        validate_certs: yes
        force_basic_auth: yes
      register: response

    - name: Display the response status code
      debug:
        var: response.status_code

    - name: Check if authentication was successful
      fail:
        msg: "Failed to authenticate to ServiceNow. Please check your credentials."
      when: response.status_code != 200