---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "your_instance"
    username: "your_username"
    password: "your_password"

  tasks:
    - name: Attempt to log into ServiceNow
      uri:
        url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/incident"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        status_code: 200
      register: response

    - name: Check login success
      debug:
        msg: "Login successful!"
      when: response.status == 200

    - name: Handle login failure
      fail:
        msg: "Failed to log into ServiceNow"
      when: response.status != 200