---
- name: Check Apache Process List
  hosts: all
  become: yes

  tasks:
  - name: Check Apache process list
    shell:
      command: "ps aux | grep apache"
    register: apache_processes

  - name: Get available CPU
    docker:
      image: busybox
      command: "top -n 1 --noheader --sort=-%cpu | awk '{print $2}'"
    register: available_cpu

  - name: Check Apache process list with available CPU
    shell:
      command: "ps aux | grep apache && ps aux | grep busybox"
    when: "apache_processes.stdout == '' or available_cpu.stdout == 'none'"
    register: apache_processes

  - name: Print Apache processes and available CPU
    debug:
      var: apache_processes.stdout
      var: available_cpu.stdout