---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - vim
          - curl
        state: present

    - name: Ensure a directory exists
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Copy a file to the server
      copy:
        src: files/example.txt
        dest: /opt/myapp/example.txt
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable a service
      systemd:
        name: sshd
        state: started
        enabled: yes