---
- name: Perform Graceful Apache Restart
  hosts: all
  become: true
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Perform a graceful restart of Apache
      command: apachectl graceful