---
- name: Apache Webserver Not Responding
  hosts: all
  become: yes

  variables:
    server_name: example.com
    port_number: 80

  tasks:
  - name: Check Apache Process List
    shell:
      command: "ps aux | grep {{ item }}"
      when: "{{ item == 'apache' }}"

  - name: Start Apache Service
    service:
      name: apache2
      state: started

  - name: Enable Apache Service
    service:
      name: apache2
      state: enabled

  - name: Restart Apache Service
    service:
      name: apache2
      state: restarted

  - name: Check Apache Process List Again
    shell:
      command: "ps aux | grep {{ item }}"
      when: "{{ item == 'apache' }}"

  become: no