---
- name: Restart Visual Studio Code
  hosts: localhost
  tasks:
    - name: Ensure Visual Studio Code is closed
      command: pkill "Code"
      ignore_errors: yes

    - name: Launch Visual Studio Code
      command: open -a "Visual Studio Code"