---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name: 
          - vim
          - curl
        state: present

    - name: Ensure Apache is installed and started
      apt:
        name: apache2
        state: present
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted