---
- name: ServiceNow Login Verification
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "your_instance"
    username: "your_username"
    password: "your_password"

  tasks:
    - name: Get Session ID from ServiceNow
      uri:
        url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/sys_user?sysparm_query=user_name={{ username }}"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        status_code: 200
      register: service_now_response

    - name: Check if login is successful
      debug:
        msg: "Login successful"
      when: service_now_response.status == 200

    - name: Handle login failure
      fail:
        msg: "Failed to log in to ServiceNow. Please check your credentials."
      when: service_now_response.status != 200