---
- name: Print AWX
  hosts: localhost
  become: yes

  tasks:
  - name: Get AWX version
    shell: |
      echo "AWX Version" > /root/awx_version
    notify: print awx

  - name: Print AWX
    shell: |
      cat /root/awx_version
    when: awx_version is defined and not empty
    notify: print awx