---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  vars:
    httpd_config_path: /etc/httpd/conf.d/
    httpd_port: 80

  tasks:
    - name: Check process list for Apache
      shell:
        args: "-c"
        when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'
      register: apache_process_list
      notify: restartapache

    - name: Run command to check if Apache is running
      shell:
        args: "systemctl status httpd.{{ item }}"
      loop: "{{ apache_process_list.stdout |split('\n') }}"

    - name: Restart Apache process if it's not running
      service:
        name: httpd.{{ item }}
        state: restarted
      when: "item not in ['status', 'running']"