---
- name: Check ServiceNow connectivity
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Test ServiceNow API connection
      uri:
        url: "https://your_instance.service-now.com/api/now/table/incident"
        method: GET
        headers:
          Accept: application/json
        validate_certs: yes
        user: your_username
        password: your_password
        force_basic_auth: yes
      register: response

    - name: Display response status code
      debug:
        msg: "Response Status Code: {{ response.status_code }}"

    - name: Fail if connection was unsuccessful
      fail:
        msg: "Failed to connect to ServiceNow. Response Status Code: {{ response.status_code }}"
      when: response.status_code != 200