---
- name: ServiceNow Login Troubleshooting Playbook
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Check if ServiceNow URL is accessible
      uri:
        url: "https://your-servicenow-instance.service-now.com"
        validate_certs: yes
        status_code: 200
      register: response
      ignore_errors: true

    - name: Debug response from ServiceNow
      debug:
        var: response.status

    - name: Ensure DNS resolution is working
      shell: nslookup your-servicenow-instance.service-now.com
      register: dns_check
      ignore_errors: true

    - name: Debug DNS check output
      debug:
        var: dns_check.stdout_lines

    - name: Check if network connectivity to ServiceNow is established
      wait_for_connection:
        host: your-servicenow-instance.service-now.com
        timeout: 30
      ignore_errors: true

    - name: Display network connectivity status
      debug:
        msg: "Network connectivity check completed with status {{ ansible_facts.network_interfaces.eth0.ipv4.address }}"

    - name: Ensure browser is up-to-date
      command: "{{ item }}"
      loop:
        - google-chrome --version
        - firefox --version
      register: browser_version
      ignore_errors: true

    - name: Debug browser versions
      debug:
        var: browser_version.results