---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  tasks:
    - name: Check Apache process list
      shell:
        cmd: "ps aux | grep apache"
        when: true

    - name: Kill inactive Apache processes
      shell:
        cmd: "pkill -9 httpd"
        when: true

    - name: Restart Apache
      service:
        name: apache2
        state: restarted