---
- name: Reset ServiceNow User Password
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate new random password
      ansible.builtin.password:
        length: 16
        chars: ascii_letters,digits,punctuation
      register: new_password

    - name: Set new password for ServiceNow user
      uri:
        url: "https://your-servicenow-instance.service-now.com/api/now/table/sys_user"
        method: PATCH
        headers:
          Accept: application/json
          Content-Type: application/json
        user: your_username
        password: your_password
        validate_certs: no
        body_format: json
        body:
          sys_id: target_user_sys_id
          user_password: "{{ new_password.password }}"
      register: reset_response

    - name: Display the new password (for testing purposes, remove in production)
      debug:
        var: new_password.password