---
- name: Apache Web Server Not Responding
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Apache Process List
      shell: "ps aux | grep apache"
      register: apache_process_list
    - name: Display Apache Process List
      debug: var(apache_process_list.stdout)