---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - vim
          - htop
        state: present

    - name: Ensure the service is running
      service:
        name: sshd
        state: started
        enabled: yes