---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check ServiceNow login
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user"
        method: GET
        headers:
          Accept: application/json
        user: your_username
        password: your_password
        validate_certs: no
      register: response

    - name: Debug response
      debug:
        var: response.status