---
- name: Restart Apache Web Server
  hosts: all
  become: true

  tasks:
  - name: Stop Apache service
    service:
      name: httpd
      state: stopped
      enabled: no

  - name: Start Apache service
    service:
      name: httpd
      state: started
      enabled: yes