---
- name: Apache Server Not Responding
  hosts: all
  become: yes

  tasks:
    - name: Check Apache Process List
      apt:
        name: apache2-utils
        state: present
      when: "{{ ansible_distribution }}"

    - name: Restart Apache Server
      service:
        name: apache2
        state: restarted
      when: "{{ ansible_distribution }}"

    - name: Verify Apache Process List
      debug:
        var: 'apache2 -n | head -1'