---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  tasks:
    - name: Check Apache Process List
      shell:
        command: "pgrep apache2"
        when: "apache2 is running"

    - name: Start and Enable Apache Service
      template:
        src: templates/service.yml.j2
        dest: /etc/systemd/system/apache2.service
        mode: '0644'
      notify: restart apache

    - name: Enable and Start Apache Service
      template:
        src: templates/service.yml.j2
        dest: /etc/systemd/system/apache2.service
        mode: '0644'
      notify: start apache

    - name: Restart Apache Service
      service:
        name: apache2
        state: restarted
      notify: restart apache

    - name: Start and Enable Apache Service by Default
      template:
        src: templates/service.yml.j2
        dest: /etc/systemd/system/apache2.service
        mode: '0644'
      notify: start apache

    - name: Enable and Start Apache Service by Default
      template:
        src: templates/service.yml.j2
        dest: /etc/systemd/system/apache2.service
        mode: '0644'
      notify: start apache