---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  tasks:
  - name: Check for Apache processes
    shell:
      msg: "Check process list for 'apache'"
      command: "ps -ef | grep apache"

  - name: Check for Apache log files
    shell:
      msg: "Check for 'apache' logs"
      command: "ls /var/log/apache2/*.log"

  - name: Restart Apache service if necessary
    shell:
      msg: "Restart Apache server if not responding"
      command: "service apache2 restart"