---
- name: Check if Apache is running
  hosts: all
  become: true
  tasks:
  - name: Check for apache process
    command: ps aux | grep apache
    register: output
  - name: Report if apache is not running
    fail:
      msg: "Apache is not running"
    when: output.stdout == ''