---
- name: Reset ServiceNow Password
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve current instance information
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user?sysparm_query=user_name={{ username }}"
        method: GET
        headers:
          Accept: application/json
          Authorization: 'Basic {{ b64encode(service_now_username + ":" + service_now_password) }}'
        validate_certs: false
      register: user_info

    - name: Reset user password
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user/{{ user_info.json.result[0].sys_id }}/password_reset"
        method: PUT
        body_format: json
        body:
          new_password: "{{ new_password }}"
        headers:
          Accept: application/json
          Authorization: 'Basic {{ b64encode(service_now_username + ":" + service_now_password) }}'
        validate_certs: false
      when: user_info.json.result | length > 0

    - name: Notify if user not found
      debug:
        msg: "User not found in ServiceNow"
      when: user_info.json.result | length == 0