---
- name: ServiceNow Login Troubleshooting Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if ServiceNow URL is reachable
      uri:
        url: "https://your_instance.service-now.com"
        method: GET
        validate_certs: yes
      register: service_now_response

    - name: Debug the response from ServiceNow
      debug:
        var: service_now_response.status_code

    - name: Ensure credentials are correct
      uri:
        url: "https://your_instance.service-now.com/api/now/table/incident"
        method: GET
        validate_certs: yes
        user: "{{ sn_user }}"
        password: "{{ sn_password }}"
      register: incident_response

    - name: Debug the response from ServiceNow API
      debug:
        var: incident_response.status_code

    - name: Check if login is successful based on status code
      fail:
        msg: "Login failed. Please check your credentials."
      when: incident_response.status_code != 200