---
- name: Apache Web Server Check
  hosts: all
  become: yes

  tasks:
    - name: Get Process List
      shell: 'ps aux | grep {{ item }}'
      register: process_list

    - name: Check Apache Status
      shell: 'apachectl -n || apachectl -k restart'
      when: process_list.item != ''
      async: 10

    - name: Display Results
      debug:
        msg: "{{ item | yank }} {{ item }}, {{ process_list.result }}"

  handlers:
  - name: apache_server_down_handler
    shell: 'echo "Apache is down" > /var/log/apache2/error.log'