---
- name: Restart Visual Studio Code
  hosts: localhost
  tasks:
    - name: Stop Visual Studio Code
      ansible.builtin.command: pkill -f "Visual Studio Code"
      ignore_errors: yes

    - name: Start Visual Studio Code
      ansible.builtin.homebrew_cask:
        name: visual-studio-code
        state: latest