---
- name: Apache Web Server Service
  hosts: localhost
  become: yes

  tasks:
    - name: Check Apache Processes
      shell:
        command: "ps aux | grep apache"
      register: apache_processes

    - name: Start/Restart Apache
      service:
        name: apache2
        state: started
      when: "{{ apache_processes.stdout == 'apache' }}"
      notify: restart apache2

    - name: Kill Apache Processes
      shell:
        command: "pkill -9 apachectl"
      register: kill_apache_processes
      when: "apache_processes.stdout != 'apache'"
      notify: restart apache2