---
- name: Check Apache Server Status
  hosts: servers
  become: yes

  tasks:
  - name: Get current system process list
    shell: "ps aux | grep apache"
    register: current_processes

  - name: Filter out non-Apache processes
    shell: "grep 'python' <<< ${current_processes.stdout}"
    register: apache_processes

  - name: Display Apache processes
    debug:
      var: apache_processes.stdout

  handlers:
  - name: restart apache service if not running
    service:
      name: httpd
      state: started
      enabled: no