---
- name: Check ServiceNow Accessibility
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure ServiceNow is accessible
      uri:
        url: https://<your_instance>.service-now.com/
        validate_certs: yes
        status_code: 200
      register: response

    - name: Debug ServiceNow response
      debug:
        var: response.status