---
- name: Apache Web Server Issue
  hosts: all
  become: yes

  roles:
    - install.apache2

  tasks:
  - debug:
      msg: "Apache process is not showing in the process list"

  - wait_for:
      uri: http://localhost:8080/status
      timeout: 10
      retries: 3
      period: 1

  - get:
      uri: https://localhost:8080/pid
      dest: /tmp/apache_pid
      mode: '0644'