---
- name: Check ServiceNow Connectivity
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Test ServiceNow login
      uri:
        url: "https://your_instance.service-now.com/api/now/table/incident"
        method: GET
        user: your_username
        password: your_password
        validate_certs: false
      register: response

    - name: Display response status code
      debug:
        var: response.status_code

    - name: Check if login was successful
      fail:
        msg: "Failed to login to ServiceNow"
      when: response.status_code != 200