---
- name: Update and install packages
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - vim
          - curl
          - git
        state: present