---
- name: Reset ServiceNow Password
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate new password
      ansible.builtin.password:
        length: 16
        chars: ascii_letters,digits,punctuation
      register: new_password

    - name: Update ServiceNow user password
      uri:
        url: "https://your-servicenow-instance.service-now.com/api/now/table/sys_user"
        method: PATCH
        headers:
          Accept: application/json
          Content-Type: application/json
        body_format: json
        body:
          user_name: your-username
          password: "{{ new_password.password }}"
        user: admin-username
        password: admin-password
        validate_certs: no
      register: response

    - name: Display new password
      debug:
        msg: "New password for {{ response.json.result.user_name }} is {{ new_password.password }}"