---
- name: Ensure Apache2 is running on 199.94.60.165
  hosts: 199.94.60.165
  become: yes
  tasks:
    - name: Install Apache2 if not already installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes