---
- name: Ensure Apache Web Server is Running
  hosts: all
  become: yes
  tasks:
    - name: Start Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Verify Apache service is running
      command: systemctl is-active httpd
      register: apache_status
      changed_when: false

    - name: Debug Apache service status
      debug:
        var: apache_status.stdout