---
- name: Apache Web Server Check
  hosts: all
  become: yes

  tasks:
    - name: Get Process List
      command: "ps aux | grep apache"
      register: process_list

    - name: Check Apache Status
      debug:
        msg: "{{ item.stdout | sub('No such file or directory', 'Apache is not running') }}"
      with_items:
        - "{{ process_list.stdout | sub('Not found', 'Apache does not exist') }}"