---
- name: ServiceNow Login Verification
  hosts: localhost
  gather_facts: no
  vars:
    snow_instance: "your_instance_name"
    snow_username: "your_username"
    snow_password: "your_password"

  tasks:
    - name: Retrieve System ID using basic authentication
      uri:
        url: "https://{{ snow_instance }}.service-now.com/api/now/table/sys_user?sysparm_query=user_name={{ snow_username }}"
        method: GET
        validate_certs: no
        user: "{{ snow_username }}"
        password: "{{ snow_password }}"
        status_code: 200
      register: response

    - name: Check if login was successful
      debug:
        msg: "Login successful. System ID: {{ response.json.result[0].sys_id }}"
      when: response.status == 200 and response.json.result | length > 0

    - name: Fail if login failed
      fail:
        msg: "Failed to log in. Check your credentials."
      when: response.status != 200 or response.json.result | length == 0