---
- name: Verify Apache Status
  hosts: all
  become: yes

  tasks:
  - name: Check Process List
    command: ps aux | grep "apache"
  - name: Verify Server Status
    uri: https://example.com
    register: apache_status
    http_code:
      status_code: 200