---
- name: Apache Web Server Not Responding
  hosts: all
  become: yes

  vars:
    server_ip: "{{ hostvars['server'] }}"

  tasks:

  - name: Check Process List for Apache
    shell:
      cmd: "ps aux | grep apache"
      restore_state: yes

  - name: Start Apache
    service:
      name: httpd
      state: started