---
- name: Apache Web Server Check
  hosts: all
  become: yes

  roles:
    - ansible-role-apache-check

  tasks:
  - name: Get process list
    command: ps -ef | grep apache2
  - name: Wait for the process to start
    wait:
      path: /usr/sbin/apachectl
      timeout: 300s