---
- name: Restart Apache
  hosts: all
  tasks:
    - name: Check if Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
      register: apache_status
    - name: Verify Apache process
      shell: ps aux | grep httpd
      register: apache_process
    - name: Restart Apache if not running
      when: apache_status.state == 'started' and apache_process is not defined
      service:
        name: httpd
        state: restarted
        enabled: yes