---
- name: Apache Web Server Issues
  hosts: webserver
  become: yes

  tasks:
  - name: Check the httpd.conf file for any errors or issues
    template:
      src: templates/httpd.conf.j2
      dest: /etc/apache2/httpd.conf.d/httpd.conf
      mode: '0644'

  - name: Check the error log files for any messages indicating Apache is not running
    stat:
      path: "/var/log/apache2/error.log"
      state: present

  - name: Start and enable the httpd service
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Restart the httpd service to ensure it starts after changes
    service:
      name: apache2
      state: restarted