---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Update package cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - vim
          - curl
          - wget
        state: present

    - name: Ensure Apache is installed and running
      apt:
        name: apache2
        state: present
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted