---
- name: Check Apache Status
  hosts: localhost
  gather_facts: yes

  roles:
    - { name: apache }
    - { name: dns }
    - { name: selinux }

  tasks:
  - debug:
      msg: "Apache Process List:"
  - debug:
      msg: "{{ item }}"
    with_items:
      - "Apache process list"
  - debug:
      msg: "Apache is not shown in the process list:"
  - debug:
      msg: "Apache is running, but no processes are showing up."