---
- name: ServiceNow Login Check and Troubleshoot
  hosts: localhost
  gather_facts: no
  vars:
    snow_instance_url: "https://your-instance.service-now.com"
    snow_username: "your_username"
    snow_password: "your_password"

  tasks:
    - name: Check if can login to ServiceNow
      uri:
        url: "{{ snow_instance_url }}/api/now/table/incident?sysparm_limit=1"
        method: GET
        user: "{{ snow_username }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
      register: snow_login_response

    - name: Debug login response
      debug:
        var: snow_login_response.status

    - name: Fail if login fails
      fail:
        msg: "Failed to login to ServiceNow"
      when: snow_login_response.status != 200