---
- name: Check Apache Web Server Status
  hosts: localhost
  become: yes

  roles:
    - ansible-role-apache

  tasks:
    - name: Check Process List for Apache
      shell:
        command: "ps aux | grep httpd"
        when: "ansible_distribution == 'centos' or ansible_distribution == 'redhat'"