---
- name: Check ServiceNow Accessibility
  hosts: localhost
  tasks:
    - name: Verify ServiceNow URL is reachable
      uri:
        url: "https://your-servicenow-instance.service-now.com"
        validate_certs: no
        return_content: yes
      register: response

    - name: Check HTTP status code
      fail:
        msg: "ServiceNow instance is not accessible. HTTP Status Code: {{ response.status_code }}"
      when: response.status_code != 200