---
- name: ServiceNow Login Test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if able to login to ServiceNow
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user"
        method: GET
        user: your_username
        password: your_password
        validate_certs: yes
      register: service_now_response

    - name: Debug response from ServiceNow
      debug:
        var: service_now_response.status