---
- name: Apache Web Server Issue
  hosts: all
  become: yes

  roles:
    - installation

  tasks:
    - name: Check Apache Process List
      shell:
        command: ps aux | grep httpd
      register: apache_process_list

    - debug:
        var: apache_process_list.stdout_lines