---
- name: Restart Apache
  hosts: all
  become: true
  tasks:
    - name: Check if Apache is running
      service: name=apache state=started enabled=yes
      register: apache_service
    
    - name: Check if Apache process exists
      shell: "pgrep -f apache"
      ignore_errors: true
      register: apache_process
      
    - name: Restart Apache service
      service: name=apache state=restarted enabled=yes
      when: apache_service.status == 'started' and not apache_process.stdout