---
- name: Restart Visual Studio Code on macOS
  hosts: localhost
  tasks:
    - name: Force quit Visual Studio Code
      command: osascript -e 'quit app "Visual Studio Code"'

    - name: Launch Visual Studio Code
      command: open -a "Visual Studio Code"