---
- name: Update and Install Packages
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - vim
          - curl
          - git
        state: present