---
- name: Restart Visual Studio Code on macOS
  hosts: localhost
  become: no
  tasks:
    - name: Kill all instances of Visual Studio Code
      ansible.builtin.command: pkill -f "Visual Studio Code"