---
- name: Restart VSCode on MacBook
  hosts: localhost
  tasks:
    - name: Kill VSCode processes
      command: pkill -f "Visual Studio Code"

    - name: Wait for a few seconds before restarting
      pause:
        seconds: 5

    - name: Start VSCode again
      command: open /Applications/Visual\ Studio\ Code.app