---
- name: Apache Web Server Not Responding
  hosts: localhost
  become: yes

  vars:
    httpd_config_file: /etc/httpd/conf.dapache.conf

  tasks:
  - name: Update Apache configuration file
    template:
      src: "{{ httpd_config_file }}"
      dest: /usr/local/apache2/conf/httpd.conf
      mode: '0644'
    notify: restart httpd

  - name: Restart Apache server
    service:
      name: httpd
      state: started