---
- name: Apache Webserver not responsive
  hosts: localhost
  become: yes

  tasks:
  - name: Check Apache status
    uri:
      url: https://example.com/httpd-status
      method: GET
      status_code: 200
      debug: True

  - name: Verify Apache process list
    uri:
      url: http://localhost/state/applications
      method: GET
      debug: True