---
- name: Reset ServiceNow User Password
  hosts: localhost
  gather_facts: no
  vars:
    snow_instance_url: "https://your_instance.service-now.com"
    admin_username: "admin_user"
    admin_password: "admin_pass"
    target_user: "target_user_to_reset"

  tasks:
    - name: Get Session Token
      uri:
        url: "{{ snow_instance_url }}/api/now/table/sys_user?sysparm_query=user_name={{ admin_username }}&sysparm_limit=1"
        method: GET
        headers:
          Accept: application/json
        user: "{{ admin_username }}"
        password: "{{ admin_password }}"
        validate_certs: no
      register: session_response

    - name: Extract User SysID
      set_fact:
        admin_sys_id: "{{ session_response.json.result[0].sys_id }}"

    - name: Reset Password for Target User
      uri:
        url: "{{ snow_instance_url }}/api/now/table/sys_user/{{ target_user }}"
        method: PATCH
        headers:
          Accept: application/json
          Content-Type: application/json
        body_format: json
        body:
          password_needs_reset: true
        user: "{{ admin_username }}"
        password: "{{ admin_password }}"
        validate_certs: no
      register: reset_response

    - name: Debug Reset Response
      debug:
        var: reset_response.json