---
- name: Restart Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Check if Apache is running
      service:
        name: apache2
        state: started
      notify:
        - restart_apache

    - name: Restart Apache
      command: systemctl restart apache2.service
      register: result
      changed_when: false

  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted