---
- name: Apache Web Server
  hosts: servers
  become: yes

  tasks:
    - name: Check if Apache is running
      shell:
        command: "systemctl status httpd"

    - name: Restart Apache service if it's not running
      shell:
        command: "sudo systemctl restart httpd"
        when: "!ansible_facts['system'] and ansible_distribution == 'CentOS' and ansible_os_version >= '7.4'"

    - name: Check process list for Apache
      shell:
        command: "ps aux | grep httpd"

    - name: Check if Apache is running
      shell:
        command: "systemctl status apache2"