---
- name: Troubleshoot ServiceNow Login Issues
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if user can reach ServiceNow instance
      uri:
        url: "https://your-servicenow-instance.service-now.com"
        validate_certs: yes
        status_code: 200
      register: response
      failed_when: response.status != 200
      changed_when: false

    - name: Display HTTP Response Code
      debug:
        msg: "HTTP Status Code: {{ response.status }}"

    - name: Check DNS resolution for ServiceNow instance
      command: nslookup your-servicenow-instance.service-now.com
      register: dns_check
      failed_when: "'canonical name' not in dns_check.stdout"
      changed_when: false

    - name: Display DNS Lookup Result
      debug:
        msg: "DNS Lookup Result:\n{{ dns_check.stdout }}"

    - name: Check if network is accessible to ServiceNow instance
      shell: ping your-servicenow-instance.service-now.com -c 4
      register: ping_result
      failed_when: "'0 received' in ping_result.stderr"
      changed_when: false

    - name: Display Ping Result
      debug:
        msg: "Ping Result:\n{{ ping_result.stdout }}"