---
- name: Restart Apache Web Server
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache service is running
      service:
        name: apache2
        state: restarted
      ignore_errors: true

    - name: Ensure Apache service is started
      service:
        name: httpd
        state: restarted
      ignore_errors: true