---
- name: Restart VSCode on MacBook
  hosts: localhost
  tasks:
    - name: Kill all instances of VSCode
      command: pkill -f "Visual Studio Code"
      ignore_errors: yes

    - name: Launch VSCode again
      shell: open -a "Visual Studio Code"