---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure a package is installed
      apt:
        name: vim
        state: present

    - name: Start and enable a service
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Copy a file to remote servers
      copy:
        src: /local/path/to/file.txt
        dest: /remote/path/to/destination.txt