---
- name: Check if Apache is running
  hosts: all
  tasks:
    - name: Check for Apache processes
      shell: ps aux | grep apache
      register: output
    - debug:
        msg: "{{ output.stdout }}"
    - name: Restart Apache
      service: name=apache state=restarted