---
- name: Check if Apache is running
  hosts: all
  tasks:
  - name: Check if Apache is running
    service:
      name: apache
      state: started
      enabled: yes
  - name: Restart Apache
    command: systemctl restart apache