---
- name: Check Apache Process List
  hosts: all
  become: yes

  vars:
    server_name: your-server-name
    port: http

  tasks:
    - name: Get process list
      get_process_list:
        path: /proc/self/fd/{{ port }}
        status: running
        quiet: no

    - name: Check Apache process list
      debug:
        var: apache_pids