---
- name: Apache Web Server Not Responding
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Check Apache Status
    debug:
      msg: "{{ item }}" | type="info"
    with_items:
      - "Apache is not running."
      - "Apache is not listening on port 80."

  - name: Restart Apache
    service:
      name: apache2
      state: restarted