---
- name: ServiceNow Login Troubleshooting
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if ServiceNow URL is reachable
      uri:
        url: "https://your-servicenow-instance.service-now.com"
        status_code: 200
      register: service_now_response

    - name: Debug response from ServiceNow
      debug:
        var: service_now_response.status

    - name: Check if credentials are valid
      uri:
        url: "https://your-servicenow-instance.service-now.com/api/now/table/incident"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        status_code: 200
      register: service_now_auth_response

    - name: Debug authentication response from ServiceNow
      debug:
        var: service_now_auth_response.status