---
- name: Apache Web Server Issue
  hosts: all
  become: true

  tasks:
    - name: Check if Apache is running
      shell: "systemctl status httpd"
      register: apache_status

    - debug: msg="Apache output:\n${apache_status.stdout}"

    - name: Restart Apache if not running
      when: not apache_status.result == 'running'
      become: true
      task: restart

    - name: Check Process List for Apache
      shell: "ps aux | grep httpd"
      register: apache_process_list

    - debug: msg="Apache process list:\n${apache_process_list.stdout}"

    - name: Restart Apache if not running from process list
      when: not apache_process_list.result == 'running'
      become: true
      task: restart

    - name: Check Process List for Apache (again)
      shell: "ps aux | grep httpd"
      register: apache_process_list_again

    - debug: msg="Apache process list:\n${apache_process_list_again.stdout}"

    - notify: Reload Apache to apply changes