---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Attempt to login to ServiceNow
      uri:
        url: "https://your_instance.service-now.com/api/now/table/incident"
        method: GET
        user: your_username
        password: your_password
        validate_certs: no
        force_basic_auth: yes
      register: response

    - name: Check if login was successful
      debug:
        msg: "Login Successful!"
      when: response.status == 200

    - name: Display error message if login failed
      debug:
        msg: "Failed to log in. Status code: {{ response.status }}"
      when: response.status != 200