---
- name: Retrieve ServiceNow Username
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Prompt for ServiceNow Username
      pause:
        prompt: "Please enter your ServiceNow username:"
      register: sn_username

    - name: Display the entered ServiceNow Username
      debug:
        msg: "The entered ServiceNow username is {{ sn_username.user_input }}"