---
- name: Check ServiceNow Accessibility
  hosts: localhost
  tasks:
    - name: Ensure ServiceNow is accessible
      uri:
        url: "https://your-servicenow-instance.service-now.com"
        method: GET
        validate_certs: yes
        status_code: 200
      register: response

    - name: Display response status
      debug:
        var: response.status