---
- name: Restart Visual Studio Code on macOS
  hosts: localhost
  become: no
  tasks:
    - name: Kill all instances of Visual Studio Code
      shell: pkill -f "Visual Studio Code"

    - name: Wait for a few seconds before restarting
      pause:
        seconds: 5

    - name: Launch Visual Studio Code
      command: open -a "Visual Studio Code"