---
- name: Ensure Apache Web Server is Running
  hosts: all
  become: yes
  tasks:
    - name: Start Apache service if it's not running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Restart Apache service to ensure it runs properly
      service:
        name: apache2
        state: restarted
        enabled: yes