---
- name: Apache Web Server Check
  hosts: all
  become: yes

  roles:
    - install.apache

  tasks:
  - block:
      - name: Wait forapache to finish
        wait_for:
          timeout: 10m
          path: /var/log/apache2/error.log
      - include: apache.yml