---
- name: Apache Web Server Check
  hosts: all
  become: yes

  roles:
    - installation

  tasks:
  - debug:
      msg: "Apache is running"
      id: apache_status

  - debug:
      msg: "Apache not shown in process list"
      id: apache_not_shown

  - name: Start Apache
    service:
      name: apache2
      state: started