---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      systemd:
        name: apache2
        state: started
        enabled: true