---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure package is installed
      apt:
        name: vim
        state: present

    - name: Copy file to remote host
      copy:
        src: /local/path/to/file.txt
        dest: /remote/path/to/destination/

    - name: Restart service
      service:
        name: nginx
        state: restarted