---
- name: Ensure Apache is running
  hosts: webservers
  become: yes
  tasks:
    - name: Start Apache service if it is stopped
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Restart Apache service to ensure it starts correctly
      service:
        name: apache2
        state: restarted