---
- name: Reset ServiceNow Password
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve user credentials from vault
      include_vars:
        file: service_now_credentials.yml
        vault: yes

    - name: Send password reset request to ServiceNow
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user?sysparm_query=user_name={{ service_now_username }}"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "Basic {{ service_now_credentials | b64encode }}"
        validate_certs: no
        status_code: 200
      register: user_info

    - name: Extract sys_id from user info
      set_fact:
        sys_id: "{{ user_info.json.result[0].sys_id }}"

    - name: Reset password for the user
      uri:
        url: "https://your_instance.service-now.com/api/now/table/sys_user/{{ sys_id }}"
        method: PATCH
        headers:
          Accept: "application/json"
          Authorization: "Basic {{ service_now_credentials | b64encode }}"
        body_format: json
        body:
          password: "{{ new_password }}"
        validate_certs: no
        status_code: 200

    - name: Notify of successful reset
      debug:
        msg: "Password for user {{ service_now_username }} has been reset."