---
- name: Apache Server Not Responding
  hosts: all
  become: yes

  tasks:
  - name: Check system logs
    debug:
      msg: "{{ item }}"

  - name: Show Apache process list
    shell:
      command: "ps aux | grep httpd"