---
- name: Troubleshoot ServiceNow Login Issue
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check network connectivity to ServiceNow instance
      uri:
        url: https://your-servicenow-instance.service-now.com
        method: GET
        validate_certs: yes
      register: response
      ignore_errors: yes

    - name: Display HTTP status code and message
      debug:
        msg: "HTTP Status Code: {{ response.status }} - Message: {{ response.msg }}"

    - name: Check DNS resolution for ServiceNow instance
      shell: nslookup your-servicenow-instance.service-now.com
      register: dns_check

    - name: Display DNS lookup results
      debug:
        msg: "{{ dns_check.stdout_lines }}"

    - name: Check if credentials are correct
      pause:
        prompt: "Please verify the username and password. Press Enter to continue."

    - name: Check browser compatibility and clear cache
      pause:
        prompt: "Check your browser settings, ensure cookies and JavaScript are enabled, and try clearing your cache. Press Enter to continue."