---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure a package is installed
      apt:
        name: nginx
        state: present

    - name: Start and enable the service
      systemd:
        name: nginx
        state: started
        enabled: yes