---
- name: Restart VSCode on MacBook
  hosts: localhost
  tasks:
    - name: Ensure VSCode is closed
      shell: |
        osascript -e 'quit app "Visual Studio Code"'
      ignore_errors: yes

    - name: Start VSCode again
      shell: open -a "Visual Studio Code"