---
- name: Install and configure Nginx
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled at boot
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom Nginx configuration file
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx to apply changes
      systemd:
        name: nginx
        state: restarted