---
- name: Check Apache Process List
  hosts: all
  become: yes

  tasks:
    - name: Check Apache process list
      shell:
        cmd:"pgrep -f 'apache'"
      register: apache_status

    - debug:
        msg: "Apache status found"
        when: apache_status.stdout is not defined

    - when: apache_status.status != 0
      action: reboot