---
- name: ServiceNow Login Task
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if credentials are valid by logging into ServiceNow
      uri:
        url: "https://your-instance.service-now.com/api/now/table/incident"
        method: GET
        user: "{{ service_now_username }}"
        password: "{{ service_now_password }}"
        validate_certs: no
        status_code: 200
      register: response

    - name: Display login result
      debug:
        msg: "Login successful"
      when: response.status == 200

    - name: Fail if login is unsuccessful
      fail:
        msg: "Failed to log into ServiceNow. Please check your credentials."
      when: response.status != 200