---
- name: Check Apache Status
  hosts: localhost
  become: yes

  roles:
    - install.apache2
    - wait_for_apache

  tasks:
    - name: Get Process List for Apache
      shell:
        command: "ps aux | grep apache"
        when: ansible_distribution == 'Red Hat' or ansible_os == 'CentOS'
      register: apachepid
      notify: restart apache2

    - debug:
        var: apachepid.stdout

    - name: Check Apache Process List
      shell:
        command: "ps aux | grep apache"
        when: ansible_distribution == 'Red Hat' or ansible_os == 'CentOS'
      register: apachepid
      notify: restart apache2