---
- name: Restart Apache Web Server
  hosts: all
  become: true
  tasks:
  - name: Check if Apache is running
    command: ps aux | grep apache
    register: result
  - name: Stop Apache
    service:
      name: httpd
      state: stopped
    when: not result.stdout.find("apache")
  - name: Start Apache
    service:
      name: httpd
      state: started
    when: result.stdout.find("apache") == -1