---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Ensure Nginx is installed and started
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Nginx is installed and started
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes