---
- name: Ensure Apache is running
  hosts: webservers
  become: yes
  tasks:
    - name: Start Apache service if it's stopped
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Restart Apache service to ensure it's running
      service:
        name: httpd
        state: restarted
        enabled: yes
      ignore_errors: true