---
- name: Restart Visual Studio Code on MacBook
  hosts: localhost
  tasks:
    - name: Stop Visual Studio Code
      shell: osascript -e 'quit app "Visual Studio Code"'

    - name: Start Visual Studio Code
      shell: open -a "Visual Studio Code"