---
- name: ServiceNow Login Check
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send GET request to ServiceNow instance
      uri:
        url: "https://your_instance.service-now.com/api/now/table/incident"
        method: GET
        validate_certs: yes
        user: your_username
        password: your_password
        force_basic_auth: yes
      register: response

    - name: Display response status code
      debug:
        var: response.status_code

    - name: Display response content
      debug:
        var: response.content