---
- name: Apache Web Server Check
  hosts: all
  become: yes

  roles:
    - ansible-role-apache-server

  tasks:
  - name: Get Apache process list
    command:
      cmd: "ps aux | grep apache"
      register: apache_processes

  - name: List Apache processes
    debug:
      msg: "{{ apache_processes.stdout | splitlines }}"